version: '3'
services: 
  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - ./compose/data/ipfs:/data/ipfs
    restart: always
    ports:
      - "4001:4001"
      - "5001:5001"
    
  ipfs-cluster:
    depends_on: 
      - ipfs
    image: ipfs/ipfs-cluster
    volumes: 
      - ./compose/data/ipfs-cluster:/data/ipfs-cluster
    restart: always
    environment: 
      CLUSTER_PEERNAME: admin
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*' # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - "127.0.0.1:9094:9094"
      - "9095:9095"
      - "9096:9096"

# volumes: 
#   ipfs_data: {}
#   ipfs-cluster_data: {}