version: '3'

networks:
    basic:

services: 
  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - ./compose/data/ipfs:/data/ipfs
    restart: always
    environment:
      - LIBP2P_FORCE_PNET=1
    networks:
      - basic
    ports:
      - "4101:4001"
      - "5101:5001"
    
  ipfs-cluster:
    depends_on: 
      - ipfs
    image: ipfs/ipfs-cluster
    volumes: 
      - ./compose/data/ipfs-cluster:/data/ipfs-cluster
    restart: always
    #environment: 
    #  - CLUSTER_PEERNAME=admin
    #   - CLUSTER_IPFSHTTP_NODEMULTIADDRESS=/dns4/ipfs0/tcp/5001
      # - CLUSTER_CRDT_TRUSTEDPEERS=* # Trust all peers in Cluster
      # - CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS=/ip4/0.0.0.0/tcp/9094 # Expose API
      # - CLUSTER_MONITORPINGINTERVAL=2s # Speed up peer discovery
      # - CLUSTER_SECRET=${CLUSTER_SECRET} # From shell variable if set
    networks:
      - basic
    ports:
      - "127.0.0.1:9190:9094"
      - "9195:9095"
      - "9196:9096"

# volumes: 
#   ipfs_data: {}
#   ipfs-cluster_data: {}
