# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  orderer0.org1.example.com:
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
        - ORDERER_GENERAL_LOCALMSPID=Org1MSP
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/peerOrganizations/org1.example.com/orderers/orderer0.org1.example.com/msp:/var/hyperledger/orderer/msp
    ports:
      - 7050:7050
  


